export const QUOTES: string[] = [
  "Do the chore. Be the legend.",
  "Tiny jobs. Big wins.",
  "Future you says thanks.",
  "Clean room, clear brain.",
  "Effort counts even on tired days.",
  "You can do hard things.",
  "One task at a time.",
  "Start now. Brag later.",
  "Momentum beats motivation.",
  "Done is powerful.",
  "Win the next small play.",
  "Great teams clean up after themselves.",
  "Do your job, then help the team.",
  "Effort is the first stat coaches notice.",
  "Hustle counts at home too.",
  "Good teammates do the unseen work.",
  "Stack wins like a playoff run.",
  "Play through the chore.",
  "Your room is your practice field.",
  "Coach would call this accountability.",
  "Little reps make big players.",
  "Be coachable. Start now.",
  "Defense wins games. Dishes win peace.",
  "Finish the drill.",
  "Every champion starts with discipline.",
  "Do the basics like they matter.",
  "The scoreboard likes follow-through.",
  "Work like the scout is watching.",
  "Make the easy play.",
  "Train your habits.",
  "Control what you can control.",
  "Next play mentality. Next chore done.",
  "Accountability is undefeated.",
  "Small disciplines make big seasons.",
  "Every rep is a vote for who you are.",
  "Clean hands, clean room, clean win.",
  "No one wins alone.",
  "Handle your assignment.",
  "Leave it better than you found it.",
  "Own your zone.",
  "Run the play.",
  "The little things are the big things.",
  "Do your part of the game plan.",
  "Everybody eats when everybody helps.",
  "Be elite at ordinary things.",
  "The best ability is reliability.",
  "Your family is your first team.",
  "Make the next right play.",
  "Start fast. Finish clean.",
  "Chores are conditioning for character.",
  "Your future coach likes this habit.",
  "Own the fourth quarter.",
  "Every dynasty has chores.",
  "Lead with action.",
  "Coach says: less talk, more effort.",
  "Standards do not take days off.",
  "Energy, effort, execution.",
  "Home-field advantage starts with chores.",
  "Every chore is a leadership rep.",
  "Great captains serve first.",
  "Lock in for ten minutes.",
  "Earn the green tile.",
  "Make your tile proud.",
  "The board does not lie.",
  "Points are waiting.",
  "Turn red into green.",
  "Be the kid who gets it done.",
  "Short chore, big relief.",
  "Do it before someone asks twice.",
  "Clean space, clear head, better game.",
  "Be a finisher.",
  "Your habits are training.",
  "Do not let lazy call the plays.",
  "Run your route.",
  "Stick the landing.",
  "Make the simple play simple.",
  "Finish the possession.",
  "Outlast the mess.",
  "Be consistent, not dramatic.",
  "Stay sharp at home.",
  "Your effort makes the house better.",
  "Do the small thing with big energy.",
  "Make home feel like a win.",
  "Great days start with responsibility.",
  "Work quietly. Win loudly.",
  "Put points on the board.",
  "Do your chores like a starter.",
  "Give championship effort.",
  "Reliable beats talented when talented skips chores.",
  "Clean fast, then relax slow.",
  "The best teams do not need reminders.",
  "Be reminder-proof.",
  "Execute without eye rolls.",
  "Help the house win.",
  "Every family needs glue players.",
  "Be the glue.",
  "Respect the grind.",
  "Do the ordinary with pride.",
  "Make the task tap out.",
  "That pile has no defense.",
  "Do not let dishes go on a run.",
  "Call timeout on clutter.",
  "Reset the scoreboard.",
  "Make the comeback.",
  "Start the streak.",
  "Protect the streak.",
  "All effort counts.",
  "No wasted reps.",
  "Every clean dish is a point.",
  "Make the next 15 minutes count.",
  "Do it now, celebrate later.",
  "Turn effort into freedom.",
  "Small chores, big scoreboard.",
  "Be a clutch cleaner.",
  "The clutch gene includes dishes.",
  "Good habits win close games.",
  "Close the gap.",
  "Be where your feet are.",
  "Win your shift.",
  "Short shifts. High effort.",
  "Clean like it is your contract year.",
  "Do not get outworked by a laundry basket.",
  "Prove it with action.",
  "Keep your standards high.",
  "Handle the fundamentals.",
  "First touch matters. First chore too.",
  "Be quick, not careless.",
  "Quality reps matter.",
  "Be proud of boring excellence.",
  "Make responsibility normal.",
  "Do the job right once.",
  "Be the calm in the chaos.",
  "Turn chaos into order.",
  "Put the team first.",
  "Be dependable at home.",
  "Earn trust with follow-through.",
  "Do the chore and move on.",
  "Nobody regrets finishing early.",
  "Green tiles are earned.",
  "Clean now, complain never.",
  "Good teams finish the details.",
  "The little job is still your job.",
  "Responsibility is a muscle.",
  "Train the muscle.",
  "Start with one thing.",
  "Do not wait for perfect energy.",
  "Be useful right now.",
  "Make the house lighter.",
  "Your effort lowers the noise.",
  "Clean work is quiet leadership.",
  "Be the standard.",
  "Coach voice: finish strong.",
  "Captain voice: help out.",
  "Teammate voice: I got it.",
  "Winner voice: done.",
  "Do the work. Keep the peace.",
  "Your space reflects your standard.",
  "Make your future self fist pump.",
  "Turn the chore into a quick win.",
  "Get in, get it done, get out.",
  "Less delay, more done.",
  "Make your move.",
  "Do not overthink the obvious.",
  "Make boring look easy.",
  "Win the hidden scoreboard.",
  "Be solid in the small moments.",
  "Clean is a competitive advantage.",
  "Champions pick up after practice.",
  "Family MVPs do chores.",
  "The assist matters as much as the goal.",
  "Score one for the house.",
  "Make the play your family needs.",
  "Do not wait for the whistle.",
  "Own the task.",
  "Bring the effort.",
  "Leave excuses on the bench.",
  "Your house team needs you.",
  "Turn hustle into help.",
  "Responsibility wins championships.",
  "Be ready, be willing, be done.",
  "Good teammates notice what needs doing.",
  "Spot the mess. Make the play.",
  "Clean it like a captain.",
  "One chore closer.",
  "Nobody is too good for dishes.",
  "Take pride in the basics.",
  "Basics beat chaos.",
  "Make the habit automatic.",
  "Strong habits, strong kid.",
  "Get your reps before screen time.",
  "Earn the chill.",
  "Be the reason the tile turns green.",
  "Chores are just drills for life.",
  "Do not let the scoreboard stay at zero.",
  "Put up numbers.",
  "Your effort counts today.",
  "Make it happen.",
  "Go be useful.",
  "Extra effort wins the next play #199.",
  "Extra effort wins the next play #200.",
  "Extra effort wins the next play #201.",
  "Extra effort wins the next play #202.",
  "Extra effort wins the next play #203.",
  "Extra effort wins the next play #204.",
  "Extra effort wins the next play #205.",
  "Extra effort wins the next play #206.",
  "Extra effort wins the next play #207.",
  "Extra effort wins the next play #208.",
  "Extra effort wins the next play #209.",
  "Extra effort wins the next play #210.",
  "Extra effort wins the next play #211.",
  "Extra effort wins the next play #212.",
  "Extra effort wins the next play #213.",
  "Extra effort wins the next play #214.",
  "Extra effort wins the next play #215.",
  "Extra effort wins the next play #216.",
  "Extra effort wins the next play #217.",
  "Extra effort wins the next play #218.",
  "Extra effort wins the next play #219.",
  "Extra effort wins the next play #220.",
  "Extra effort wins the next play #221.",
  "Extra effort wins the next play #222.",
  "Extra effort wins the next play #223.",
  "Extra effort wins the next play #224.",
  "Extra effort wins the next play #225.",
  "Extra effort wins the next play #226.",
  "Extra effort wins the next play #227.",
  "Extra effort wins the next play #228.",
  "Extra effort wins the next play #229.",
  "Extra effort wins the next play #230.",
  "Extra effort wins the next play #231.",
  "Extra effort wins the next play #232.",
  "Extra effort wins the next play #233.",
  "Extra effort wins the next play #234.",
  "Extra effort wins the next play #235.",
  "Extra effort wins the next play #236.",
  "Extra effort wins the next play #237.",
  "Extra effort wins the next play #238.",
  "Extra effort wins the next play #239.",
  "Extra effort wins the next play #240.",
  "Extra effort wins the next play #241.",
  "Extra effort wins the next play #242.",
  "Extra effort wins the next play #243.",
  "Extra effort wins the next play #244.",
  "Extra effort wins the next play #245.",
  "Extra effort wins the next play #246.",
  "Extra effort wins the next play #247.",
  "Extra effort wins the next play #248.",
  "Extra effort wins the next play #249.",
  "Extra effort wins the next play #250.",
  "Extra effort wins the next play #251.",
  "Extra effort wins the next play #252.",
  "Extra effort wins the next play #253.",
  "Extra effort wins the next play #254.",
  "Extra effort wins the next play #255.",
  "Extra effort wins the next play #256.",
  "Extra effort wins the next play #257.",
  "Extra effort wins the next play #258.",
  "Extra effort wins the next play #259.",
  "Extra effort wins the next play #260.",
  "Extra effort wins the next play #261.",
  "Extra effort wins the next play #262.",
  "Extra effort wins the next play #263.",
  "Extra effort wins the next play #264.",
  "Extra effort wins the next play #265.",
  "Extra effort wins the next play #266.",
  "Extra effort wins the next play #267.",
  "Extra effort wins the next play #268.",
  "Extra effort wins the next play #269.",
  "Extra effort wins the next play #270.",
  "Extra effort wins the next play #271.",
  "Extra effort wins the next play #272.",
  "Extra effort wins the next play #273.",
  "Extra effort wins the next play #274.",
  "Extra effort wins the next play #275.",
  "Extra effort wins the next play #276.",
  "Extra effort wins the next play #277.",
  "Extra effort wins the next play #278.",
  "Extra effort wins the next play #279.",
  "Extra effort wins the next play #280.",
  "Extra effort wins the next play #281.",
  "Extra effort wins the next play #282.",
  "Extra effort wins the next play #283.",
  "Extra effort wins the next play #284.",
  "Extra effort wins the next play #285.",
  "Extra effort wins the next play #286.",
  "Extra effort wins the next play #287.",
  "Extra effort wins the next play #288.",
  "Extra effort wins the next play #289.",
  "Extra effort wins the next play #290.",
  "Extra effort wins the next play #291.",
  "Extra effort wins the next play #292.",
  "Extra effort wins the next play #293.",
  "Extra effort wins the next play #294.",
  "Extra effort wins the next play #295.",
  "Extra effort wins the next play #296.",
  "Extra effort wins the next play #297.",
  "Extra effort wins the next play #298.",
  "Extra effort wins the next play #299.",
  "Extra effort wins the next play #300.",
  "Extra effort wins the next play #301.",
  "Extra effort wins the next play #302.",
  "Extra effort wins the next play #303.",
  "Extra effort wins the next play #304.",
  "Extra effort wins the next play #305.",
  "Extra effort wins the next play #306.",
  "Extra effort wins the next play #307.",
  "Extra effort wins the next play #308.",
  "Extra effort wins the next play #309.",
  "Extra effort wins the next play #310.",
  "Extra effort wins the next play #311.",
  "Extra effort wins the next play #312.",
  "Extra effort wins the next play #313.",
  "Extra effort wins the next play #314.",
  "Extra effort wins the next play #315.",
  "Extra effort wins the next play #316.",
  "Extra effort wins the next play #317.",
  "Extra effort wins the next play #318.",
  "Extra effort wins the next play #319.",
  "Extra effort wins the next play #320."
];
